Repository ucsb-cs156-f22/f22-7pm-happycows, pull requests merged in 2022-11, with the labels that each got.

#11 Lawrence - Frontend placeholder for milk the cows
  .gitignore
  frontend/src/main/components/Jobs/MilkTheCowsJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
Labels: 5, f22-7pm-4

#10 Change the footer to get the source repository from API call
  frontend/src/fixtures/systemInfoFixtures.js
  frontend/src/main/components/Nav/Footer.js
  frontend/src/main/layouts/BasicLayout/BasicLayout.js
  frontend/src/stories/components/Footer/Footer.stories.js
  frontend/src/tests/components/Nav/Footer.test.js
Labels: 10, f22-7pm-3

#8 Modified SystemInfo by creating sourceRepo string
  src/main/java/edu/ucsb/cs156/happiercows/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImpl.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImplTests.java
Labels: 10, f22-7pm-3

#29 Fixed bug Toast says "Cow bought" even when no cow was bought
  frontend/src/main/pages/PlayPage.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
Labels: bug, 10, f22-7pm-3

#17 RY-add placeholder jobs for update cow health and instructor report
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/InstructorReport.java
  src/main/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealth.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/InstructorReportJobTests.java
  src/test/java/edu/ucsb/cs156/happiercows/jobs/UpdateCowHealthJobTests.java
Labels: 10, f22-7pm-4

#21 Limit CI runs to when relevant files are modified
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/30-frontend-tests.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/34-frontend-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
Labels: f22-7pm-3, STAFF: ready for review

#28 Edit the Join Commons column in Home Page
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/pages/HomePage.test.js
Labels: f22-7pm-3, STAFF: ready for review

#34 Nm - Changes milk cows job to post
  src/main/java/edu/ucsb/cs156/happiercows/controllers/JobsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/JobsControllerTests.java
Labels: 5, f22-7pm-4

#33 nm-tk Changes all table backgrounds to white
  frontend/src/main/components/OurTable.js
Labels: f22-7pm-4

#42 Nm-tk Fixes mutation coverage issue
  frontend/src/main/components/OurTable.js
Labels: f22-7pm-4

#32 Frontend changes to allow admin to launch "Update Cow Health" and "Instructor Report"
  frontend/src/main/components/Jobs/InstructorReportJobForm.js
  frontend/src/main/components/Jobs/JobComingSoon.js
  frontend/src/main/components/Jobs/MilkTheCowsJobForm.js
  frontend/src/main/components/Jobs/UpdateCowHealthJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 20, f22-7pm-4, MERGE when CI/CD is green

#43 KC - update CommonsTable to have correct accessors for /allplus endpoint
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/utils/commonsUtils.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  frontend/src/tests/utils/commonsUtil.test.js
Labels: f22-7pm-3, FIXME: CI/CD Failure

#47 Added changes to get full coverage for PlayPage.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: f22-7pm-3

#41 Removed "The game will end on"
  frontend/src/main/components/Commons/CommonsOverview.js
Labels: 5, f22-7pm-4

#49 Fix cow sale toast when no cows are salable
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 10, f22-7pm-3
