Repository ucsb-cs156-f22/f22-7pm-happycows, pull requests merged in 2022-12, with the labels that each got.

#54 Lawrence - Delete .DS_Store again
  .DS_Store
Labels: f22-7pm-4, STAFF: ready for review

#63 Calculate days elapsed
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
Labels: 10, f22-7pm-4, MERGE when CI/CD is green

#65 pc/ry/ag - add userCommons plus endpoint to make username available on leaderboard
  frontend/src/fixtures/leaderboardFixtures.js
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/UserCommonsPlus.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: f22-7pm-4

#53 Added CowDeathTable react component, storybook, fixures and tests
  frontend/src/fixtures/cowDeathFixtures.js
  frontend/src/main/components/CowDeaths/CowDeathTable.js
  frontend/src/stories/components/CowDeaths/CowDeath.stories.js
  frontend/src/tests/components/CowDeaths/CowDeathTable.test.js
Labels: f22-7pm-3, STAFF: ready for review

#57 IL - Add another field to the Commons: Carrying Capacity. This is the number of cows the commons can support
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/fixtures/userCommonsFixtures.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10, f22-7pm-3

#68 Nm tk -Fix background issue mutation bug w/ CSS in place test
  frontend/src/main/components/OurTable.js
  frontend/src/tests/components/OurTable.test.js
Labels: 5, f22-7pm-4

#62 IL - After Carrying Capacity is added to backend, add it to the AdminListCommons page
  frontend/src/fixtures/commonsPlusFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/stories/components/Commons/CommonsTable.stories.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 20, f22-7pm-3

#64 IL - After Carrying Capacity added to backend (issue #13), add it to the frontend Create / Update operations
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: f22-7pm-3, STAFF: ready for review
